name: Test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: cargo test
  test_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: cargo test
  test_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: cargo test